application: life-a-game
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

builtins:
- deferred: on

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
- name: numpy
  version: "1.6.1"
- name: ssl
  version: latest

